### ISSUE TITLE
SDWriter中定义的环境变量长度与uboot中不一致，导致CRC出错

### ISSUE THREAD

**Issue by 1020165558** [OpenNuvoton/NUC980_SDWriter#1]
SDWriter中定义的环境变量长度与uboot中不一致，导致CRC出错。SDWriter中的长度是0x10000.uboot中的是0x20000

**Comment by yachen** [comment]
Hi,

Fixed in b64180c, thanks a lot.

Sincerely,

Yi-An Chen
